CREATE TABLE IF NOT EXISTS tasks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(150)                            NOT NULL,
    description  VARCHAR(500),
    status       VARCHAR(32)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    due_date     TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    project_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_projects FOREIGN KEY (project_id) REFERENCES projects (id)
)